/********************************************************************
* TMhs3Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TMhs3Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTMhs3Dict();
extern void G__cpp_setup_inheritanceTMhs3Dict();
extern void G__cpp_setup_typetableTMhs3Dict();
extern void G__cpp_setup_memvarTMhs3Dict();
extern void G__cpp_setup_globalTMhs3Dict();
extern void G__cpp_setup_memfuncTMhs3Dict();
extern void G__cpp_setup_funcTMhs3Dict();
extern void G__set_cpp_environmentTMhs3Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TMhs3.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TMhs3DictLN_TClass;
extern G__linked_taginfo G__TMhs3DictLN_TBuffer;
extern G__linked_taginfo G__TMhs3DictLN_TMemberInspector;
extern G__linked_taginfo G__TMhs3DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__TMhs3DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TMhs3DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TMhs3DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TMhs3DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TMhs3DictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__TMhs3DictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TMhs3DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TMhs3DictLN_TCanvas;
extern G__linked_taginfo G__TMhs3DictLN_TThreadframe;
extern G__linked_taginfo G__TMhs3DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TMhs3DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TMhs3DictLN_TH1F;
extern G__linked_taginfo G__TMhs3DictLN_TPad;
extern G__linked_taginfo G__TMhs3DictLN_TMhs3;

/* STUB derived class for protected member access */
