// keithley1.idl : keithley1.exe 的类型库源

// 此文件将由 MIDL 编译器处理以产生
// 类型库 (keithley1.tlb)。

[ uuid(6ED50F2A-1138-496D-BE4C-55943EF3A37F), version(1.0) ]
library keithley1
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	//  Ckeithley1Doc 的主调度接口
	
	[ uuid(B036E18F-59E5-466A-B6CF-D357C36BCAF7) ]
	dispinterface Ikeithley1
	{
		properties:
			
		methods:
	};

	//  Ckeithley1Doc 的类信息
	
	[ uuid(0D9B53D0-03E1-45E9-B372-7128E96857F6) ]
	coclass keithley1
	{
		[default] dispinterface Ikeithley1;
	};
};
